/** /api/rumors/search + /api/rumors/feed — in-character tavern gossip
 * generated by `openclaw agent`, no Twitter dependency. */

import type { FastifyInstance } from "fastify";

import { callAgent } from "../openclaw-agent.ts";

interface Rumor {
  id: string;
  text: string;
  author: string;
  handle: string;
  avatar: string;
  likes: number;
  retweets: number;
  time: string;
}

async function generateRumors(topic: string, max: number): Promise<{ ok: boolean; rumors?: Rumor[]; error?: string }> {
  const t = (topic || "").trim() || "the adventurer";
  const prompt =
    "You are Gus the tavern keeper compiling rumours you overheard tonight " +
    `about: "${t}". ` +
    `Produce exactly ${max} short rumours. Each MUST be on its own line in this ` +
    "EXACT format, nothing else (no preamble, no epilogue, no markdown, no numbering):\n\n" +
    "RUMOR: <anonymous source handle, 1-3 words, evocative> | <one short gossip sentence in " +
    "the tavern's voice — cryptic, colourful, medieval-fantasy tone, NOT actual news>\n";
  const reply = await callAgent(prompt, { thinking: "off", timeoutMs: 60000 });
  if (!reply) return { ok: false, error: "agent unavailable" };
  const nowIso = new Date().toISOString();
  const rumors: Rumor[] = [];
  for (const raw of reply.split("\n")) {
    const line = raw.trim();
    if (!line.toLowerCase().startsWith("rumor:")) continue;
    const body = line.slice(line.indexOf(":") + 1);
    const parts = body.split("|").map((p) => p.trim());
    if (parts.length < 2) continue;
    const handle = parts[0]?.slice(0, 40) ?? "";
    const text = parts[1]?.slice(0, 280) ?? "";
    const hashId = `gen-${Math.abs(hashString(line)) % 1_000_000_000}`;
    rumors.push({
      id: hashId,
      text,
      author: handle,
      handle,
      avatar: "",
      likes: 0,
      retweets: 0,
      time: nowIso,
    });
    if (rumors.length >= max) break;
  }
  return { ok: true, rumors };
}

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h << 5) - h + s.charCodeAt(i);
    h |= 0;
  }
  return h;
}

export async function registerRumorRoutes(app: FastifyInstance): Promise<void> {
  app.get<{ Querystring: { q?: string; max?: string } }>(
    "/api/rumors/search",
    async (request) => {
      const q = request.query.q ?? "";
      const max = Math.max(1, Math.min(Number.parseInt(request.query.max ?? "6", 10) || 6, 12));
      return generateRumors(q, max);
    },
  );

  app.get<{ Querystring: { max?: string } }>("/api/rumors/feed", async (request) => {
    const max = Math.max(1, Math.min(Number.parseInt(request.query.max ?? "6", 10) || 6, 12));
    return generateRumors("", max);
  });
}
